/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guides: [
    {
      type: 'category',
      label: 'Guides',
      link: { type: 'doc', id: 'guides/summary' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        },
      ],
    },
  ],
  setups: [
    {
      type: 'category',
      label: 'Setups',
      link: { type: 'doc', id: 'setups/summary' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'setups',
        },
      ],
    },
  ],
  samples: [
    {
      type: 'category',
      label: 'Setups',
      link: { type: 'doc', id: 'samples/overview' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'samples',
        },
      ],
    },
  ],
  references: [
    {
      type: 'category',
      label: 'References',
      link: { type: 'doc', id: 'references/summary' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'references',
        },
      ],
    },
  ],
};

module.exports = sidebars;
