/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guides: [
    {
      type: 'category',
      label: 'Guides',
      link: { type: 'doc', id: 'guides/summary' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        },
      ],
    },
  ],
  manuals: [
    {
      type: 'category',
      label: 'Manuals',
      link: { type: 'doc', id: 'manuals/summary' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'manuals',
        },
      ],
    },
  ],
  references: [
    {
      type: 'category',
      label: 'References',
      link: { type: 'doc', id: 'references/summary' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'references',
        },
      ],
    },
  ],
};

module.exports = sidebars;
