/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

const guides = [
  {
    type: 'category',
    label: 'Guides',
    link: { type: 'doc', id: 'guides/readme' },
    items: [
      {
        type: 'autogenerated',
        dirName: 'guides',
      },
    ],
  },
]

const references = [
  {
    type: 'category',
    label: 'References',
    link: { type: 'doc', id: 'references/readme' },
    items: [
      {
        type: 'autogenerated',
        dirName: 'references',
      },
    ],
  },
]

const js = [
  {
    type: 'autogenerated',
    dirName: 'api/js',
  },
]

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guides: [
    {
      type: 'category',
      label: 'Guides',
      link: { type: 'doc', id: 'guides/readme' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        },
      ],
    },
  ],
  setups: [
    {
      type: 'category',
      label: 'Setups',
      link: { type: 'doc', id: 'setups/readme' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'setups',
        },
      ],
    },
  ],
  references: [
    {
      type: 'category',
      label: 'References',
      link: { type: 'doc', id: 'references/readme' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'references',
        },
      ],
    },
  ]
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  // tutorialSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Guides',
  //     link: { type: 'doc', id: 'guides/readme' },
  //     items: [
  //       {
  //         type: 'autogenerated',
  //         dirName: 'guides',
  //       },
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Setups',
  //     link: { type: 'doc', id: 'setups/readme' },
  //     items: [
  //       {
  //         type: 'autogenerated',
  //         dirName: 'guides',
  //       },
  //     ],
  //   },
  // ],
};

module.exports = sidebars;
