ApiVersion: $NANOCL_VERSION

Namespace: global

# See all options:
# https://docs.next-hat.com/references/nanocl/objects/cargo
Cargoes:
- Name: my-cargo
  Container:
    Image: ghcr.io/next-hat/nanocl-get-started:latest

# See all options:
# https://docs.next-hat.com/references/nanocl/objects/resource
Resources:
- Name: deploy-example.com
  Kind: ncproxy.io/rule/$NCPROXY_VERSION
  Data:
    Rules:
    - Domain: deploy-example.com
      Network: All
      Locations:
      - Path: /
        Target:
          Key: my-cargo.global.c
          Port: 9000
